# --- Basics --- #

title: Dr. Steffen Wöll
description: Postdoctoral Researcher at SFB 1199 / Leipzig University

# --- Local development options ---
# If hosted locally set url and baseurl (Danger!)

# URL without trailing slash
# url: "https://example.com"

# Should be an empty string
# baseurl: ""

# --- Navbar --- #

navbar-links:
  Publications: "publications/"
  Activities: "activities/"
  Journal: "/journal/"
  Contact: "contact/"
#  More:
#  - Projects: "projects"
#  - Tags: "tags"

# Navbar image, must be square
# Remove for no image
avatar: "/img/pro_av.webp"

# Logo in top-left corner instead of title text
# title-img: /path/to/image

# --- Footer --- #

# Danger: Do not delete 'name' parameter
author:
name:

# Select active social links
# If adding new link also edit _data/SocialNetworks.yml
social-network-links:
  home:
  email: "steffen.woell@uni-leipzig.de"
  rss: true
  researchgate: Steffen-Woell
  # orcid: 0000-0003-1582-6078
  # blog: dysnomia/
  # mastodon: "@SteffenWoell"
  instagram: streetart_leipzig/
  soundcloud: w-a_s

# Share links shown in posts
share-links-active:
  twitter: false
  facebook: false
  linkedin: false

# Format of link to website in footer
url-pretty: "steffenwoell.github.io"

# --- Misc --- #

excerpt_length: 250

# Character used to separate site title and description in HTML and RSS feed title
title-separator: "-"

# Ruby date format
date_format: "%-d %B %Y"

# Output options
timezone: "Europe/Germany"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10
paginate_path: "journal/page:num"

kramdown:
  input: GFM

# Default YAML values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false # add social buttons to blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags on index page & make tags on blog posts clickable
link-tags: true

# Exclude files from production site
exclude:
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Vagrantfile
  - projects.md
  - _posts/markdown-examples.md

# Include plugins on production site
plugins:
 # - jekyll-paginate
