# --- General options --- #

# Name of website
title: Dr. Steffen Wöll

# Brief description of website
description: Postdoctoral Researcher at SFB 1199 / Leipzig University

# --- Local development options ---
# If website is hosted locally rather than on GitHub, uncomment the next two parameters to set the url and # baseurl (Danger!)

# url is website domain URL without trailing slash
# url: "https://example.com"

# baseurl should be an empty string
# baseurl: ""

# --- Navigation bar options --- #

# List of links in navigation bar
navbar-links:
  Publications: "publications/"
  Activities: "activities/"
  Journal: "/journal/"
  Imprint: "imprint/"
#  More:
#  - Projects: "projects"
#  - Tags: "tags"

# Image to show in navigation bar - must be square (width = height)
# Remove for no image in navbar
avatar: "/img/swp.webp"

# Image logo in top-left corner instead of title text
# title-img: /path/to/image

# --- Background colour/image options --- #

# Color values can be any valid CSS

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#404040"
hover-col: "#404040"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of color

# navbar-img: "/img/bgimage.webp"
# footer-img: "/img/bgimage.webp"
# page-img: "/img/bgimage.webp"

# --- Footer options --- #

# Danger: Do not delete "name" parameter
author:
name:

# Select active Social Network Links.
# If adding new link also edit _data/SocialNetworks.yml
social-network-links:
  home:
 # email: "steffen.woell@uni-leipzig.de"
  rss: true
  researchgate: Steffen-Woell
  orcid: 0000-0003-1582-6078
  blog: dysnomia/
  mastodon: "@SteffenWoell"
  instagram: streetart_leipzig/
  soundcloud: w-a_s

# Select which share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  linkedin: false

# How to display link to website in footer
url-pretty: "steffenwoell.github.io"

# --- Comments --- #

# Fill in Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# If using JustComments fill in API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Staticman comments, fill in repository, branch, and endpoint
staticman:
  repository : # GitHub username/repository eg. "user/rep"
  branch     : master # If not using `master` branch also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
    # If using reCaptcha, must also set these parameters in staticman.yml
    siteKey  : # If using own site key, must apply for one on G00gle
    secret   : # ENCRYPT password at https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Excerpt Word Length
# Truncates excerpt to specified number of words on index page
excerpt_length: 120

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%-d %B %Y"

# --- No need to touch anything below --- #

# Output options
timezone: "Europe/Germany"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: "journal/page:num"

kramdown:
  input: GFM

# Default YAML values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags on index page and make tags on each post clickable
link-tags: false

# Excluded files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - favicon.old.ico
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - projects.md
  - tags.html
  - README.md
  - Vagrantfile
  - staticman.yml

# Included plugins on production site
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
